services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: dds_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5433:5432"

  web:
    build: .
    command: gunicorn dds_manager.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./staticfiles:/app/staticfiles
    depends_on:
      - db

    ports:
      - "8000:8000"

    environment:
      - IN_DOCKER=True
      - DB_HOST=db                
      - DB_PORT=5432             
      - DB_NAME=dds_db            
      - DB_USER=postgres          
      - DB_PASSWORD=1 

      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=123

    
    

volumes:
  postgres_data:

